 
version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'ptarmigan'
      MYSQL_USER: 'ptarmigan'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 3306

  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379