site_name: ptarmigan
repo_url: https://github.com/VilhelmPrytz/ptarmigan
edit_uri: /tree/master/docs

nav:
  - Introduction: 'index.md'
  - Installation: 'installation.md'
  - Development: 'development.md'

theme: readthedocs
markdown_extensions:
    - admonition:
